config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  resources :homes
  resources :products
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category

    validates :name, presence: true
    validates :description, presence: true
    validates :quantity, presence: true, numericality: true
    validates :price, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def create
        @category = Category.create(category_params)
        if @category.save
            redirect_to :categories
        else
            render :new
        end
    end

    def new
        @category = Category.new
    end

    def edit
        set_category
    end

    def show
        set_category
    end

    def update
        set_category
        @category.update(category_params)
        redirect_to :categories
    end

    def destroy
        set_category
        @category.destroy
        redirect_to :categories
    end


    private 

    def category_params
        params.require(:category).permit(:name)
    end

    def set_category
        @category = Category.find(params[:id])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        if params[:category_id].present?
            @products = Product.where(category_id: params[:category_id])
        else
            @products = Product.all
        end
    end

    def show
        set_product
    end
    
    def new
        @categories = Category.all
        @product = Product.new
    end
    
    def edit
        set_product
        @categories = Category.all
    end
    
    def create
        @product = Product.create(product_params)
        
        if @product.save
            redirect_to :products
        else
            render :new
        end
    end

    def update
      set_product
      if @product.update(product_params)
        redirect_to :products
      else
        render :new
      end
    end

    def destroy
        set_product
        @product.destroy
        redirect_to :products
    end

    private

    def product_params
        params.require(:product).permit(:name, :description, :quantity, :price, :category_id)
    end

    def set_product
        @product = Product.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/edit.html.erb
<%= simple_form_for @category, url: category_path, html:{class:'form'}, remote: true, validate: true do |f| %>
    <div class="inps-div">
      <%= f.label :'Kategori:', class:'lbl' %>
      <%= f.text_field :name, class:'inp' %>
    </div>
    <div class="inps-div">
    <%= f.button :submit, "Değiştir" , class:'inp'%>
    </div>
<% end %>
  

app/views/categories/index.html.erb
<%= "Kategori Listesi" %>
<br/>
<br/>
<table>
    <tr>
        <th>Kategori</th>
        <th>Yok Et</th>
        <th>Değiştir</th>
    </tr>
    <% @categories.each do |c| %>
        <tr>
            <td>
                <%= link_to c.name, category_path(c) %>
            </td>
    
            <td> 
            <%= link_to category_path(c.id), method: :delete, data:{:confirm => "Silcen mi?"}  do %> 
                <i class="fa-regular fa-circle-xmark"></i>
                <% end %>
            </td>
            <td> <%= link_to edit_category_path(c.id) do %>
                <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>
  
<br/>
<br/>
<%= link_to "Ekle", new_category_path %>

app/views/categories/new.html.erb
<%= simple_form_for @category, url: categories_path, html:{class:'form'}, method: :post do |f| %>
    <div class="inps-div">
      <%= f.label :'Kategori:', class:'lbl' %>
      <%= f.text_field :name, class:'inp' %>
    </div>
    <div class="inps-div">
    <%= f.button :submit, "Ekle" , class:'inp'%>
    </div>
<% end %>
  

app/views/categories/show.html.erb
Kategori Detayları
<h2>Kategori: <%= @category.name %></h2>

app/views/homes/index.html.erb
<h2 style="text-align:center">HOME HOME SWEET HOME</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forogren</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navs-div">
    <%= link_to "Anasayfa", homes_path, class: "navs-link" %>
    <%= link_to "Ürünler", products_path, class: "navs-link" %>
    <%= link_to "Kategoriler", categories_path, class: "navs-link" %>
  </div>
    <hr>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= simple_form_for @product, url: product_path, html:{class:'form'}, remote: true, validate: true do |f| %>
    <div class="inps-div">
      <%= f.label :Ürün, class:'lbl' %>
      <%= f.text_field :name, class:'inp' %>
    </div>
    <div class="inps-div">
      <%= f.label :Açıklama, class:'lbl' %>
      <%= f.text_area :description, class:'inp' %>
    </div>
    <div class="inps-div">
      <%= f.label :Adet, class:'lbl' %>
      <%= f.number_field :quantity, class:'inp' %>
    </div>
    <div class="inps-div">
      <%= f.label :Fiyat, class:'lbl' %>
      <%= f.number_field :price, step: 0.01, class:'inp' %>
    </div>
    <div class="inps-div">
    <%= f.label :Kategori, class: 'lbl' %>
    <%= f.collection_select :category_id, @categories, :id, :name, { prompt: '~' }, { class: 'inp' } %>
  </div>
    <div class="inps-div">
    <%= f.button :submit, "Değiştir" , class:'inp'%>
    </div>
<% end %>
  

app/views/products/index.html.erb
<%= "Ürün Listesi" %>
<br/>
<br/>
Kategoriye Göre Filtrele:
<br/>
<%= form_tag(products_path, method: "get") do %>
    <%= label_tag(:category_id, "Kategori:") %>
    <%= select_tag(:category_id, options_for_select([["Hepsi", ""], *Category.all.map { |c| [c.name, c.id] }])) %>
    <%= submit_tag("Filtrele") %>
  <% end %>
<br/>
<table>
    <tr>
        <th>Ürün</th>
        <th>Açıklama</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Kategori</th>
        <th>Yok Et</th>
        <th>Değiştir</th>
    </tr>
    <% @products.each do |p| %>
        <tr>
            <td> <%= link_to p.name, product_path(p)%> </td>
            <td> <%= p.description%> </td>
            <td> <%= p.quantity%> </td>
            <td> <%= number_to_currency(p.price, unit:'₺', precision:2,) %> </td>
            <td><%= p.category.name %></td>
            <td> 
            <%= link_to product_path(p.id), method: :delete, data:{:confirm => "Silcen mi?"}  do %> 
                <i class="fa-regular fa-circle-xmark"></i>
                <% end %>
            </td>
            <td> <%= link_to edit_product_path(p.id) do %>
                <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>
  
<br/>
<br/>
<%= link_to "Ekle", new_product_path %>

app/views/products/new.html.erb
<%= simple_form_for @product, url: products_path, html: { class: 'form' }, method: :post do |f| %>
  <div class="inps-div">
    <%= f.label :Ürün, class: 'lbl' %>
    <%= f.text_field :name, class: 'inp' %>
  </div>
  <div class="inps-div">
    <%= f.label :Açıklama, class: 'lbl' %>
    <%= f.text_area :description, class: 'inp' %>
  </div>
  <div class="inps-div">
    <%= f.label :Adet, class: 'lbl' %>
    <%= f.number_field :quantity, class: 'inp' %>
  </div>
  <div class="inps-div">
    <%= f.label :Fiyat, class: 'lbl' %>
    <%= f.number_field :price, step: 0.01, class: 'inp' %>
  </div>
  <div class="inps-div">
    <%= f.label :Kategori, class: 'lbl' %>
    <%= f.collection_select :category_id, @categories, :id, :name, { prompt: 'Kategori Seçiniz' }, { class: 'inp' } %>
  </div>
  <div class="inps-div">
    <%= f.button :submit, "Ekle", class: 'inp' %>
  </div>
<% end %>

app/views/products/show.html.erb
Ürün Detayları
<div style="display:flex; flex-direction:column; align-items:center">
<h2 style="text-align:center"> <%=@product.name%> </h2>
<p> <strong><%=@product.category.name%> Kategorisinde</strong> </p>
<p> <%=@product.description%> </p>
<p> <%=@product.quantity%> Adet</p>
<p> <%= number_to_currency(@product.price, unit:'₺', precision:2,) %> </p>
</div>